### PR TITLE
Feature/back to top section links

### PR DESCRIPTION
**Pull request by klepas**
Adds back to section index links for all sections after the first section (dependant on the `headline` key).

@joolswood could you take a quick look over the wording here — any edits (eg ‘back to table of contents’)? (:

Screenshot:

screen shot 2016-12-05 at 5 11 47 pm

### CODE REVIEW

**Review by dominikwilkowski — APPROVED** [review]

**Comment by joolswood** [comment]
Hey @klepas @dominikwilkowski can we change this to `Back to contents`? I'd prefer to use the same wording as we already have on the page, and also not to confuse things further about the usage of the word 'section'. Much to my chagrin I've had to use that word in the local nav example to try and explain it better (one of the examples that may still need to be uploaded from my local).

Also, can we move it to the footer of the component rather than the header?

**Comment by klepas** [comment]
Hey @joolswood — looks like this go merged before these edits were applied.

I’ll do that now.

> Also, can we move it to the footer of the component rather than the header? They’re effectively in the footer; they come before the next `h2`, and are just visually floated to the right.

**Comment by joolswood** [comment]
> Also, can we move it to the footer of the component rather than the header?
> > They’re effectively in the footer; they come before the next h2, and are just visually floated to the right.

They're coming up for me as floating between a H2 and the abstract line:
screen shot 2016-12-07 at 12 09 34 pm

**Comment by klepas** [comment]
> They're coming up for me as floating between a H2 and the abstract line:

Yea… my latest PR on this feature fixes that… in all but like 2 cases. :S

**Pull request merged**
