### PR TITLE
First attempt at updating cf related configs

### PR DESCRIPTION
**Pull request by klepas**
@aussielunix, could you take a peak at this?

At the moment it’s not building on the endpoint successfully. :S

### CODE REVIEW

**Comment by aussielunix** [comment]
:eyes: at it now

**Comment by aussielunix** [comment]
@klepas nice work.

Only thing obvious for now is that you are not setting a node version anywhere for CI.

In [circle.yml](https://github.com/AusDTO/dto-design-guide/blob/feature/update-cf-deploy-setup/circle.yml#L2)  this is the block where you can use the CircleCI builtins to configure the Ubuntu 14.04 virtual machine that your builds happen in.
Take a look at https://circleci.com/docs/language-nodejs/ for some help with nodejs.

**Comment by klepas** [comment]
Yesssss!

**Comment by klepas** [comment]
Thanks @aussielunix (:

**Review by dominikwilkowski — APPROVED** [review]

**Pull request merged**
